return {
	cornavydestro = {
		activatewhenbuilt = true,
		buildangle = 16384,
		buildpic = "CORROY.DDS",
		buildtime = 10600,
		canmove = true,
		collisionvolumeoffsets = "0 -5 5",
		collisionvolumescales = "40 40 140",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		energycost = 8000,
		explodeas = "mediumexplosiongeneric",
		floater = true,
		footprintx = 4,
		footprintz = 4,
		health = 4800,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.02757,
		maxdec = 0.02757,
		metalcost = 1010,
		minwaterdepth = 12,
		movementclass = "BOAT4",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/CORNAVYDESTRO.s3o",
		radardistance = 800,
		radaremitheight = 40,
		script = "Units/CORNAVYDESTRO.cob",
		seismicsignature = 0,
		selfdestructas = "mediumexplosiongenericSelfd",
		sightdistance = 600,
		speed = 56,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 280,
		waterline = 0,
		customparams = {
			model_author = "Johnathan Crimson",
			normaltex = "unittextures/cor_normal.dds",
			subfolder = "CorShips",
			unitgroup = "weaponsub",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "0.0580749511719 -0.062504465332 -0.201034545898",
				collisionvolumescales = "33.2652587891 20.5109710693 79.4415893555",
				collisionvolumetype = "Box",
				damage = 3360,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 4,
				metal = 480,
				object = "Units/corroy_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				damage = 4032,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 240,
				object = "Units/cor5X5D.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:barrelshot-medium",
				[2] = "custom:waterwake-small",
				[3] = "custom:bowsplash-small",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "shcormov",
			},
			select = {
				[1] = "shcorsel",
			},
		},
		weapondefs = {
			aa_missile = {
				areaofeffect = 48,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				castshadow = false,
				cegtag = "missiletrailaa",
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-tiny-aa",
				firestarter = 70,
				flighttime = 1.9,
				impulsefactor = 0.123,
				metalpershot = 0,
				model = "cormissile.s3o",
				name = "Light g2a missile launcher",
				noselfdamage = true,
				range = 765,
				reloadtime = 1.7,
				smokecolor = 0.95,
				smokeperiod = 6,
				smokesize = 4.8,
				smoketime = 12,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "xplomed2",
				soundhitwet = "splshbig",
				soundstart = "rockhvy2",
				startvelocity = 400,
				texture1 = "null",
				texture2 = "smoketrailaa",
				tolerance = 10000,
				tracks = true,
				turnrate = 63000,
				turret = true,
				weaponacceleration = 150,
				weapontimer = 5,
				weapontype = "MissileLauncher",
				weaponvelocity = 750,
				damage = {
					vtol = 115,
				},
			},
			naval_plasma_cannon = {
				areaofeffect = 86,
				avoidfeature = false,
				craterareaofeffect = 0,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.15,
				explosiongenerator = "custom:genericshellexplosion-medium",
				gravityaffected = "true",
				impulsefactor = 0.123,
				name = "HeavyCannon",
				noselfdamage = true,
				range = 710,
				reloadtime = 3,
				soundhit = "xplomed2",
				soundhitwet = "splssml",
				soundstart = "cannhvy1",
				turret = true,
				weapontype = "Cannon",
				weaponvelocity = 320,
				damage = {
					default = 385,
					vtol = 45,
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "VTOL",
				def = "naval_plasma_cannon",
				maxangledif = 270,
				fastautoretargeting = true,
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				badtargetcategory = "VTOL",
				def = "naval_plasma_cannon",
				maxangledif = 270,
				fastautoretargeting = true,
				onlytargetcategory = "SURFACE",
				
			},
			[3] = {
				badtargetcategory = "NOWEAPON LIGHTAIRSCOUT",
				def = "aa_missile",
				fastautoretargeting = true,
				onlytargetcategory = "VTOL",
			},

		},
	},
}
